---
title: "Beyond the Dataset"
description: |
  Deep dive into the Big Five Personality Test and General Applications/Trends in Society
output: html_document
date: "2023-08-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyverse)
library(dplyr)
library(distill)
library(kableExtra)
library(stringr)
```

NOTICE: This section is currently a work-in-progress. I'll be continuously adding various bits and pieces, and you'll absolutely encounter awkward sentences + spelling/grammar mistakes. Welcome to the slow process of analysis, and enjoy your stay (while it lasts)! 

### Definitions

When discussing the Big Five, there are several bits of terminology that needs to be understood: 

**Trait**: “Person’s typical style of thinking, feeling, and acting in different kinds of situations and at different times”  (Costa and McCrae 1988). Traits can be used to predict certain behaviors. 

**Personality**: “Pattern of relatively permanent traits and unique characteristics that give both consistency and individuality to a person’s behavior.” They’re acquired through life experiences and are relatively stable. 

**Temperament**: “Physical, mental, and emotional traits people are born with.”^[<a href="https://hrdqstore.com/blogs/hrdq-blog/difference-behavior-personality-temperament" target="_blank">Source.</a>]

Many consider temperament as a subset of personality.^[<a href="https://en.wikipedia.org/wiki/Temperament" target="_blank">Source.</a>] However, temperament is considered to have their own model called the CBQ (Children’s Behavior Questionnaire) with the following three traits: 

- Negative Affectivity (Neuroticism)
- Surgency extroversion (Extroversion)
- Effortful Control (Conscientiousness) 

Notice the overlap between CBQ and Big Five - we’re only missing openness and agreeableness. However, despite the similarities, we will not be separating personality and temperament, as the Big Five aims to cover personality traits while integrating temperament into the mix. 

I'm also going to clarify the definition of extroversion. The Big Five uses Eysenck’s concept of extroversion rather than Jung’s. 

**Eysenck:** Extroverts gain and recharge their mental energy from external stimuli, such as social interaction. Introverts prefer to shield themselves from external stimuli and recharge their mental energy by withdrawing themselves.^[<a href="https://www.introvertpalace.com/blogs/news/the-psychology-of-introversion-eysenck-s-theory-of-arousal" target="_blank">Source.</a>]
 

**Jung:** Extroverts seek action and sensory input from the external world, using their experiences to influence their thoughts, beliefs, and actions. Introverts immerse themselves in their internal environment, through reflection, dreaming, and keeping their 'head in the clouds' to influence their actions.^[<a href="https://fractalenlightenment.com/31622/life/jungs-theory-of-introvert-and-extrovert-personalities
" target="_blank">Source.</a>]
 

This clarification may be redundant -- many people have only heard of Eysenck’s version of extroversion. However, I still find value in acknowledging Jung, especially because Eysenck built his definition off of Jung’s. 


### Big Five Personality Test - Origins  

“Can you find a taxonomy to describe human personality?” 

That’s the idea that started the Big Five Personality Test.^[<a href="https://www.discovermagazine.com/mind/understanding-the-big-five-personality-traits" target="_blank">Source.</a>] After all, humans were greedy for more, desperate to understand human personality, and longed to map it out qualitatively.  

Since the 1880s, scientists have been interested in personality. But, it only became official in 1936 when Gordon Allport and Henry Odbert conducted the first study of personality. They gathered 18000 personality-describing words from the Webster’s Dictionary, then narrowed it down to 4504 adjectives to describe non-physical characteristics. This created the first ‘personality wordbank’ -- a 'formal' way to describe personality.

Through the work of Cattell, Tupes and Christal, Fiske, Norman, Smith, McCrae and Costa^[<a href="www.thomas.co/resources/type/hr-guides/what-are-big-5-personality-traits" target="_blank">Source.</a>], and many others, the test has undergone several revisions, expansions, and improvements. However, the purpose and the ideas within the test remain.^[<a href="https://www.retorio.com/blog/big-5-history-psychometric-test" target="_blank">Source.</a>]  


### Strengths 

There’s a lot of reasons why the Big Five is such a popular test and remains at the forefront of personality research. 

1. The traits the Big Five measures are relatively stable during adulthood. 

As we grow older, our traits are going to naturally develop and change. For example, you tend to have higher conscientiousness and agreeableness and lower neuroticism, extroversion, and openness. This is mainly because people tend to have more responsibilities (i.e. family, job, etc.) as they age and eventually learn to build traits to adapt. This is called the maturation effect.^[<a href="https://pubmed.ncbi.nlm.nih.gov/18028073/" target="_blank">Source.</a>]
 

After adolescence, people’s traits tend to stabilize, ensuring there are distinct behavior patterns to analyze. This consistency (leading to replicability) is desirable for scientists. 

2. Widely accepted by the scientific community 

Many scientists have conducted studies to confirm the validity and reliability of the Big Five Personality Test. This includes Krueger and Eaton (2010), Kamarulzaman and Nordin (2012), and Satow (2021). Using confirmatory factor analysis, invariance analysis, and various other empirical tests, studies have shown that the Big Five test can account for "80% of personality variance"^[<a href="https://www.alleydog.com/glossary/definition.php?term=Lexical+Hypothesis">Source.</a>] and is most widely accepted test within this niche. 

3. Very easily repeatable 

Scientists value repeatability. Got a fascinating result? Make sure to do the experiment 2 more times, just in case something was off! 

The Big Five test is generally delivered as a 50-question Likert scale test. It can easily be printed and distributed in a similar manner to thousands of participants, ensuring consistency between studies. 

4. Simplicity and Generalization

As a result of constantly improving the Big Five personality test, the traits we’ve selected are:

a) Easy to understand and specific - In English, these traits are clearly defined and simple.
b) Mutually exclusive - Makes it easy to quantify. 
c) Generalizable - These traits are universal and can generally apply to any culture.

Together, these strengths make the Big Five the default when considering personality. 

### Applications in Society 

You can apply the Big Five personality traits to predict future behavior.  

A popular example is that high conscientiousness and emotional stability (low neuroticism) are correlated with stronger job performance and higher wages. This information could potentially shape businesses’ hiring and recruiting practices, as they’re already begun to use the Myers–Briggs Type Indicator (MBTI) to narrow down the applicant pool. 

This has the potential to be a positive addition: Bad hires can cost “up to 30% of the employee’s first-year earnings” - a significant loss for the business if “46% of newly-hired employees [are] deemed failures”.^[<a href="https://www.retorio.com/blog/big-5-history-psychometric-test" target="_blank">Source.</a>] However, since the Big Five personality test is a self-assessment, lying on it becomes a trivial task. 

High conscientiousness is also a general indicator for superior academic performance. This is likely because conscientiousness and agreeableness were “positively related with all four learning styles (synthesis analysis, methodical study, fact retention, and elaborative processing)”. It was also concluded that the Big Five “explained 14% of the variance in [a student’s] grade point average” whereas “learning systems explained an additional 3%”, establishing a clear connection between personality traits and learning styles improving one’s academics.^[<a href="https://www.researchgate.net/publication/251531386_The_Big_Five_personality_traits_learning_styles_and_academic_achievement" target="_blank">Source.</a>] 

Certain traits can also correlate with specific learning styles. In a study, the study identified four types of learning styles: 

**Meaning Directed**: Focuses on self-regulated learning and critical information synthesis, developing independent thinking and establishing connections between ideas and concepts. 

**Reproduction Directed**: Focuses on memorizing and rehearsing information, directed by an external figurehead (teacher). Typically, the information is memorized to be reproduced/recalled on a test. 

**Application Directed**: Focuses on understanding and learning to meet certifications of accreditations, focus on real-world application and examples. 

**Undirected**: Enjoys cooperative learning, directed by an external figurehead, has difficulty finding ways to approach their studying and self-regulation. 

These learning styles are apart of Vermunt’s Inventory of Learning and has been validated through several studies.^[<a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5554702/" target="_blank">Source.</a>] However, it has fallen out of favor with the public since the introduction of the VARK (visual, aural, read/write, and kinesthetic).^[The VARK model has many disbelievers for various reasons. See more here: Hederich-Martínez, C. y Camargo Uribe, A. (2019). Critical Review of J.Vermunt’s Learning Pattern Model. Revista Colombiana de Educación, 77, 1-25. doi: https://doi.
org/10.17227/rce.num77-9469.]  

The correlations between Big Five traits and VARK learning styles are shown in the table below. A '+' represents a positive correlation, a '-' represents a negative correlation, and a blank cell means that there is no correlation between the two variables. 

```{R correlationtable}

ctable = data.frame("." = c('Extroversion', 'Conscientiousness', 'Neuroticism', 'Agreeableness', 'Openness'),
                    'Meaning Directed' = c('$+$', '$+$','$-$', "", '$+$'), 
                    'Reproduction Directed' = c('$+$','$+$',"$-$", '$+$',''), 
                    'Application Directed' = c('$+$','$+$','','$+$', "$+$"),
                    'Undirected' = c("", '$-$','$+$','', "$-$") 
                    )

colnames(ctable) <- str_replace_all(colnames(ctable), "[:punct:]", " ")

kable(ctable, caption = "Correlation between Big Five and Vermunt's learning styles") %>%
  kable_styling()


```

This connection could potentially allow teachers to better assist struggling students, using different tactics that best suit their needs. For example, neurotic and undirected students could benefit from individual attention or asking other students to form groups and help teach each other the concepts. Teachers could opt for more independent assignments for conscientious students, or give more thorough instructions to students who are more agreeable.  

There are also various patterns with Big Five traits and an individual's health. First, conscientiousness is the strongest predictor for reduced morality — being a conscientious person makes you 30% less likely to die, compared to other people. This is because these people tend to make better health choices, as they’re more likely to stay fit, cooperate when given medical advice, have better sleeping habits, and are less likely to smoke. Conscientiousness is also tied to having more supportive relationships, thriving at work, and having better stress management.^[<a href="https://www.wellandgood.com/conscientiousness-longevity/" target="_blank">Source.</a>] 

People with Alzheimer's typically see a significant decrease in conscientiousness and large increase in neuroticism. Decreases in extroversion, openness, and agreeableness were also spotted. These Big Five traits could assist an early diagnosis for the patient. In addition, Heroin and Ecstasy users showed patterns when testing their Big Five traits. Heroin users had high neuroticism and openness while Ecstasy had high extroversion and openness. Both also had lower agreeableness and conscientiousness. 

Mental disorders are also linked to neuroticism -- especially during adolescence. 

### Limitations of the Big Five Test

Despite the Big Five’s numerous applications in society, rigorous tests for reliability and validity, and general acceptance within the scientific community, there are various criticisms of the test. 

**Lexical Hypothesis**

One of the biggest criticisms of the Big Five test is its basis of lexical hypothesis. Lexical hypothesis assumes that “the most important personality traits are encoded as words…. and that the analysis of [these words] may lead to a scientifically acceptable personality model”.^[<a href="https://www.researchgate.net/publication/298930186_The_lexical_approach_in_personality_psychology_A_review_of_personality_descriptive_taxonomies" target="_blank">Source.</a>] Hence, by using language (or for the Big Five, a dictionary) as a resource, researchers can create a list of important personality traits to judge people off of. 

People are against the lexical hypothesis for various reasons: 

Verbal descriptors result in social bias (i.e. people consciously or unconsciously choose traits that align with what society deems as ‘good’. For example, people might say they’re ‘agreeable’ because society prefers agreeable people more). This can greatly skew the data as Extroversion, Agreeableness, and Neuroticism become invalid as researchers can not ensure that people will answer honestly and objectively.^[You can see how this has affected this data set, most notably with agreeableness and openness.]

Others also deem personality as ‘too complex’ to be encoded into a singular word or used in everyday language. We may require more detail to fully express what characteristics we want to capture, as language may not be an adequate vessel to describe the human condition and personality. Traits can also be too ambiguous – they could be misunderstood or the meaning of the word could change overtime. 

The lexical hypothesis also has little scientific backing. The terms used with lexical hypotheses were developed for daily use, and could represent different meanings/perceptions rather than the definition researchers aim to use. Furthermore, tests to validate the lexical hypothesis are deemed ‘unscientific’.^[<a href="https://web.archive.org/web/20120507121610/http://www.psychsystems.net/Publications/1996/2.%20uncovering%20the%20nomothetic%20from%20the%20idiographic_Westen_jrnl%20of%20research%20in%20pers%201996.pdf" target="_blank">Source.</a>] 


**(In)correct Approaches**

There are two approaches for the Big Five: 

**Etic:** “Traits are universal, regardless of the environment, culture or context” 
**Emic:**”Traits are culture and context-specific” 

Often, Big Five studies use the Etic approach, generalizing the results to encompass the entirety of the human population, instead of narrowing their scope. 

The Etic (or universal) approach was led by Eysenck, as he emphasized how the Big Five traits are ‘biological’ and universal to every human language, and would appear regardless of one’s culture or environment.^[<a href="https://www.researchgate.net/publication/335834113_Big_Five_Traits_A_Critical_Review" target="_blank">Source.</a>]  

The Emic (or local) approach believes that the cultures heavily shape personality traits. For example, with the test’s origins stemming from lexical hypothesis, the current model proposes a Western-centric view of personality traits, rather than a holistic view. 

Thus, the question becomes: Do you value a generalized and universal model to encompass the entire human condition? Or, do you take a more personalized approach, envisioning how one’s environment can influence their behavior? 

**Culture Differences** 

Various cultures, such as Korean, Mexican, Indian, Filipino and Arabic, believe that there are many traits which are very important to them and only exist within their culture. Therefore, if we were to utilize the Etic approach, there may be crucial personality traits that are left out as a result of the Big Five’s Western-centric development.

This belief has been explored in Chinese culture and

This idea has actually been explored by Chinese researchers who replicated the origins of the Big Five test by applying the idea of lexical hypothesis to Chinese. This resulted in a completely different quiz with different traits — Chinese Personality Assessment Inventory (CPAI) — that was tailored for a Chinese audience.^[<a href="https://www.researchgate.net/publication/233846335_The_English_Version_of_the_Chinese_Personality_Assessment_Inventory" target="_blank">Source.</a>]  

The Chinese Personality Assessment Inventory (CPAI), containing four major personality factors:

1. Social potency (leadership, divergent thinking, novelty, extroversion)
2. Dependability (responsibility, optimism vs pessimism, face^[The public image you project - your ‘face’ in society.], locus of control)
3. Accommodation (Family orientation, self vs society, defensiveness, graciousness, logical vs affective orientation) 
4. Interpersonal relatedness (individual vs social, harmony, discipline, traditionalism vs modernity)

There is some overlap with the Big Five.

- Societal potency corresponds to extroversion and openness
- Dependability corresponds to neuroticism and conscientiousness 
- Accommodation corresponds to agreeableness^[<a href="https://www.linkedin.com/pulse/big-five-vs-chinese-four-next-thing-personality-silk-aps-assoc-cipd/" target="_blank">Source.</a>]

Although there are some similarities, it's clear that the Chinese do not value the same things as Western audiences. For example, there are many openness-related traits, such as divergent thinking and novelty within the social potency category. However, openness is not a seperate category as it functions “in a complex context than a distinct construct” when compared to the Western environment.^[<a href="https://www.researchgate.net/publication/233846313_Relevance_of_Openness_as_a_Personality_Dimension_in_Chinese_Culture_Aspects_of_its_Cultural_Relevance" target="_blank">Source.</a>] Furthermore, the CPAI also associates extroversion with openness - these traits tend to be more distinct for Western audiences. 

Furthermore, the definition of openness can vary depending on one’s culture. Openness requires breaking free of tradition and embracing new ideas. They must be motivated by aesthetic sensitivity rather than rules — an idea which can be discouraged in Asian cultures. It also begs the question: Is their opinion truly what they think, or were they just taught to think that? If they’re taught to think that, does that matter? Is that part of their personality or just a byproduct of their society? 

Issues of an Etic approach are also found in Arabic language and culture when attempting to create a more indigenous test, where differences in results were prominent enough to birth a completely new sixth trait: religiosity. EXPAND ON THIS

**Sex Differences**

The Big Five Personality Test results also seem to change depending on one’s sex. When collecting results in Turkey, men were “more imaginative and inquisitive” compared to women. This is likely caused by the patriarchal culture within Turkey as they have very strict gender roles; men were able to pursue what they wanted while women were shoehorned into rigid lifestyles. So, men would likely cultivate openness traits, while women would stray away from them.^[<a href="https://dergipark.org.tr/en/download/article-file/1122830" target="_blank">Source.</a>] 

We can also see this occur on a smaller scale within Western societies by analyzing the stereotypical socialization of girls and boys. In Canada, China, Finland, Germany, Poland, and Russia, men tend to be “more assertive and risk-taking than women”, hence scoring high on extrovertism and openness, whereas women were more “anxious and tender-minded”, scoring higher in scored higher in neuroticism, agreeableness, and conscientiousness” compared to men.^[<a href="https://bpspsychub.onlinelibrary.wiley.com/doi/full/10.1111/bjop.12668" target="_blank">Source.</a>] EXPAND ON THIS - what socialization happens? when women have assertiveness, they're seen as undesirable, prim and proper, etc. 

When analyzing results from 55 nations around the world, the trend changes slightly: women scored higher in neuroticism, agreeableness, extroversion, and conscientiousness. However, men scored higher in assertiveness and openness.^[<a href="https://sahajaonline.com/character-personality/personality-strengths-guide/can-we-change/" target="_blank">Source.</a>] EXPAND ON THIS - are women encouraged more in other societies aside from western ones? Socioeconomic factors also influenced gender differences, where the largest differences measured were larger in healthy, rich and gender-egalitarian cultures. Furthermore, men in developed world regions were “less neurotic, extroverted, conscientious and agreeable, compared to men in less developed world regions”. The personality of women did not significantly differ based on their socioeconomic status. 

Of course, there are various reasons for these differences in personality based on sex, such as social roles and evolutionary reasons. For example, due to parental investment, men are more open to risks and tend to be more socially dominant, while women tend to be more nurturing and cautious. However, with these results, can you measure and generalize certain traits such as openness and extroversion accurately when it is actively being manipulated by cultural, societal, and evolutionary factors?  

**Lack of Representation**

Although this test samples hundreds of locations, it’s not completely representative of the population it claims to show. This is because a majority of our data comes from Western, educated, industrialized, rich and democratic (WEIRD) populations. Less developed countries (such as the ones within Africa) are often glossed over and represent a tiny amount of data points. 

A clear example of this is the data set that I’ve been analyzing. When we look at the data points on the map (to find trends between countries), it’s clear that much of Africa has been omitted from the data.^[Recall that I removed any countries that had less than 10 responses to reduce skewing and better visualize the data.] It brings the reliability of the data set into question: can we rely on WEIRD populations to make generalizations, and assume it will be correct? Are these results universally applicable?

For the Big Five, studies have shown that non-WEIRD populations **do not follow the same trends as WEIRD populations**. In fact, for low and middle income countries, Big Five personality questions fail to measure the personality traits they’re built for, and have low validity. This is a huge contrast to the high validity seen in internet surveys from the same low/middle income countries.  

Previously, it has been mentioned that conscientiousness and emotional stability are more correlated with income. It also intuitively makes sense — if you can work hard and have good stress management, workers could perform their job better. Yet, when analyzing non-WEIRD populations, it was seen that conscientiousness was not a predictor for increased income. Instead, only emotional stability and openness were predictors. However, openness items “poorly differentiate from other items… one cannot exclude that this result is driven by systematic responses biases” and other external factors. One must remain cautious between correlation and causation. 

During the process of surveying non-WEIRD populations, it should also be noted that errors may occur due to the quality of translation (i.e. wording of question, how they are interpreted within a specific culture) via an enumerator, as there was effort to adapt to respondents with lower cognitive ability. Thus, the impact of an enumerator’s face-to-face interactions with respondents should be taken into consideration. It was also noted that less educated populations had lower interest in taking the survey, as their incentives and expectations for the survey may be completely different than a respondent in a WEIRD country who is taking the Big Five test for fun. 

Even after categorizing respondents into different categories (e.g. sexes, countries), there still seems to be constantly shifting answers instead of a general trend. Assuming that we continue to use an ‘etic’ approach, the reliability of the test can be called into question, as there are inconclusive results. 

**Variability of Tests**

The Big Five Personality Test has dozens of different versions. Some contain 44 questions, some contain 25, 50, or even 60. In addition, each test will use different questions to poll respondents. In non-Western countries, people will also have translators which could twist the meaning of the question. 

Of course, the test will always attempt to measure the respondent’s personality and there are standardized subtraits within each trait (i.e. the subtrait assertiveness within the trait extroversion). However, it’s possible that person 1 taking test version A with 44 questions could receive a different result than if they took test version B with 50 different questions with a translator. 

### Possible Improvements to the Big Five Tests

### Spin-off Tests

### Connections to MBTI


rmarkdown::render('C:/Users/sophi/OneDrive/Documents/Personal/bigfive/docs/beyond.Rmd', output_file = 'C:/Users/sophi/OneDrive/Documents/Personal/bigfive/docs/beyond.html')
